### ISSUE TITLE
Two blobs created have the same data handle

### ISSUE THREAD

**Issue by YanYas** [MyCaffe/MyCaffe#7]
I tried creating 2 Blobs and adding them together, just to understand how the system works.

But I find the gpu_data handle = 2 for both the Blob I created. The result is that the Input1's value is added to both sides of the operation. I think.

```
        public Blob<float> CuSca(float Input1)
        {
            var myDevice = new CudaDnn<float>(0, DEVINIT.CURAND);
            var myLog = new Log("");
            var inputArray = new float[1];
            inputArray[0] = Input1;
            var myData = new SimpleDatum(1, 1, 1, inputArray, 0, 1);
            return new Blob<float>(myDevice, myLog, myData, true, true, false);
        }

        public Blob<float> TheAdd(Blob<float> Input1, Blob<float> Input2)
        {
            Input1.Cuda.add(Input1.count(), Input1.gpu_data, Input2.gpu_data, Input1.gpu_data);
            return Input1;
        }

        public float[] myBlobAdditonTest(float input1, float input2)
        {
            var scalar1 = CuSca(input1);
            Console.WriteLine("Scalar 1 gpu_data = {0}", scalar1.gpu_data);
            var scalar2 = CuSca(input2);
            Console.WriteLine("Scalar 2 gpu_data = {0}", scalar2.gpu_data);
            var cudaRes = TheAdd(scalar1, scalar2).Clone();
            return cudaRes.Cuda.GetMemoryFloat(cudaRes.gpu_data);
        }

        public void MyTest()
        {
            var myResult = myBlobAdditonTest(1.0f, 0.5f)[0];
            Console.WriteLine(myResult.ToString());
        }

```

I've tried this while putting the same CudaDNN Device and log object  in both Blobs, but this doesn't make a difference. I've also tried creating a new output Blob for the result, but this makes no difference either.

How should this be done?

Thanks in advanced,

Yy

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

The reason that you are seeing this behavior is because in your code above you are using two different instances of the CudaDnn object (see the first line of CuSca).  

Each CudaDnn instance maintains its own instance of an underlying kernel which manages all memory and all other low-level states such as cuDNN objects, etc.  Typically there is only one CudaDnn instance used per thread and the methods provided by the CudaDnn only work on the GPU memory allocated by that particular CudaDnn instance.

We have created an updated sample that steps through your sample above, but does so making sure to only use a single instance of the CudaDnn object.  See https://github.com/MyCaffe/MyCaffe-Samples/blob/master/BlobUsage/BlobUsage/Program.cs
 for the code.

Hope this helps!

**Comment by YanYas** [comment]
Perfect! Thanks for going through the trouble of adding that sample.

Yy
